version: "3"
services:
    tests:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - db
        container_name: api-test-container
        working_dir: /app
        restart: always
        command: bash -c "npm install -g jest && npm run test && npm run build && npm start"
        ports:
            - "8080:8080"
        links:
            - db

    db:
      image: db
      container_name: postgres-api-test
      build:
        context: .
        dockerfile: Dockerfile_db
      restart: always
      environment:
        POSTGRES_PASSWORD: some_password
        POSTGRES_USER: some_user
        POSTGRES_DB: test
      volumes:
            - ./pgdata:/var/lib/postgresql/data
            - ./dumps:/dumps
      ports:
            - "5432:5432"

